### ISSUE TITLE
simply swap some keys

### ISSUE THREAD

**Issue by ohmyhusky** [esrille/new-keyboard#10]
Hi bro, I'd like to swap some keys position on this keyboard, (ex : cmd swap with option) is it possible to have this done without programming?

**Comment by ShikiOkasaka** [comment]
With the current firmware, you have to modify the source code to swap key positions.

We might add another mode to the modifier key layouts set by FN-F6 to swap GUI(cmd, windows) and ALT(option) in the future firmware, though:
http://www.esrille.com/keyboard/modifiers.html

**Comment by cyl19910101** [comment]
Is is possible to provide customise swap functions with this keyboard's hardware (especially the memory)? Is so, I think maybe I should try to learn this source code and provide such feature, since I had never wrote firmware before, I guess I will learn a lot of things from your code, so exciting~

**Comment by ShikiOkasaka** [comment]
You can modify the flash program memory at runtime; so theoretically it is quite possible. However due to the limited flash memory size of PIC18F4550, you will have to remove unused portions from the standard USB NISSE firmware firstly before adding more features.

Note the Bluetooth/USB NISSE, currently available only in Japan, uses PIC18F47J53 which has larger flash memory, and maybe we will introduce a richer framework that eases your keymap customization in the future.

**Comment by KrakenEXE** [comment]
Update?

**Comment by ShikiOkasaka** [comment]
We're likely to release a new USB NISSE firmware with more free space mainly for the customers in the United States. Also if you have a specific request, feel free to open another issue.

**Comment by ShikiOkasaka** [comment]
The new USB NISSE controller board using PIC18F47J53 has been released.
https://www.esrille.com/keyboard/news.html#2020-05-07

Note we maintain NISSE firmware configurations for both PIC18F4550 and PIC18F47J53 at this point.
