### ISSUE TITLE
Option to invert numbers and symbols on the number row

### ISSUE THREAD

**Issue by jeandeaual** [esrille/new-keyboard#15]
It would be nice to have an option to invert numbers and symbols on the number row, like on the [French layout](https://en.wikipedia.org/wiki/AZERTY), [Spanish layout](https://commons.wikimedia.org/wiki/File:KB_Spanish.svg), [some QWERTZ layouts](https://en.wikipedia.org/wiki/QWERTZ) or the [Programmer Dvorak layout](https://www.kaufmann.no/roland/dvorak/).

This would mostly be useful for programmers, people using a [Compose key](https://en.wikipedia.org/wiki/Compose_key) to input special characters or to add hardware support for Programmer Dvorak.

I think this means inverting the shift modifier when a number row key is pressed.
The main issue is with the behavior of the Caps Lock key:

* With Programmer Dvorak, Caps Lock works for the number row (e.g. pressing Caps Lock then `[` outputs 7. This is useful when you want to input multiple numbers in a row.
* With the French layout, Caps Lock works for the number row AND special character keys not in the number row such as `$`, `*`, `!`, etc.

I'm not sure which approach would be the best here.

What do you think about this possible feature?

**Comment by ShikiOkasaka** [comment]
Adding European keyboard layouts has been a low priority since we do not export NISSE to Europe directly.
To support the standard 102 keyboard layout, the firmware needs to support another mode that can generate KEY_NON_US_BACKSLASH scan code. The required change would be very small anyway.
Device drivers should be able to handle generic features in each country beyond this.
